version: "3"

services:
  url-shortener:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - ./dbdata:/app/dbdata
      - ./static:/app/static
      - ./config.yaml:/app/config.yaml
      - ./src:/app/src
    working_dir: /app/src
    env_file:
      - .env
    environment:
      - CGO_ENABLED=0
    command:
      - /go/bin/fresh
    restart: always
