version: "3"

services:
  url-shortener:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - ./dbdata:/app/dbdata
      - ./static:/app/static
      - ./config.yaml:/app/config.yaml
      - ./src:/app/src
    working_dir: /app/src
    env_file:
      - .env
    environment:
      - CGO_ENABLED=0
    networks:
      - redis-net
    depends_on:
      - redis
    command:
      - /go/bin/fresh
    restart: always

  redis:
    image: redis:5.0.3-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data


networks:
  redis-net:
    driver: bridge

volumes:
  redis-data:
